### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 401: {

### ISSUE THREAD

**Issue by Clairewangxiaotong** [tardis-dev/tardis-python#11]
WHEN I try to download csv from trdis,I met this bug,Is there anyone who can help me ?

import asyncio
import csv
from tardis_client import TardisClient, Channel
from tardis_dev import datasets
import os
os.environ["http_proxy"]  = "http://127.0.0.1:10809"
os.environ["https_proxy"] = "http://127.0.0.1:10809"

from tardis_dev import datasets, get_exchange_details
import logging

# optionally enable debug logs
# logging.basicConfig(level=logging.DEBUG)

exchange = 'deribit'
exchange_details = get_exchange_details(exchange)

# iterate over and download all data for every symbol
for symbol in exchange_details["datasets"]["symbols"]:
    # alternatively specify datatypes explicitly ['trades', 'incremental_book_L2', 'quotes'] etc
    # see available options https://docs.tardis.dev/downloadable-csv-files#data-types
    data_types = symbol["dataTypes"]
    symbol_id = symbol["id"]
    from_date =  symbol["availableSince"]
    to_date = symbol["availableTo"]
    # skip groupped symbols
    # print('111',symbol_id)
    if symbol_id in ['PERPETUALS', 'SPOT', 'FUTURES']:
        continue
    print(f"Downloading {exchange} {data_types} for {symbol_id} from {from_date} to {to_date}")
    # each CSV dataset format is documented at https://docs.tardis.dev/downloadable-csv-files#data-types
    # see https://docs.tardis.dev/downloadable-csv-files#download-via-client-libraries for full options docs
    datasets.download(
        exchange = exchange,
        data_types = data_types,
        from_date =  from_date,
        to_date = to_date,
        symbols = [symbol_id],
        # TODO set your API key here
        api_key = "YOUR_API_KEY",
        # path where CSV data will be downloaded into
        download_dir = "./datasets",
    )

----------------------------------------------------------------------------------------------------------------------------------------------------
D:\Anaconda\envs\tqsdk\python.exe C:/Users/112233/Desktop/NN/option/main.py
D:\Anaconda\envs\tqsdk\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\Anaconda\envs\tqsdk\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
D:\Anaconda\envs\tqsdk\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Downloading deribit ['trades', 'incremental_book_L2', 'quotes', 'book_snapshot_5', 'book_snapshot_25', 'options_chain', 'liquidations', 'book_ticker'] for OPTIONS from 2019-03-30T00:00:00.000Z to 2022-11-02T00:00:00.000Z
Traceback (most recent call last):
  File "C:/Users/112233/Desktop/NN/option/main.py", line 33, in <module>
    datasets.download(
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\tardis_dev\datasets\download.py", line 41, in download
    asyncio.get_event_loop().run_until_complete(
  File "D:\Anaconda\envs\tqsdk\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\tardis_dev\datasets\download.py", line 86, in download_async
    done.pop().result()
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\tardis_dev\datasets\download.py", line 144, in _reliably_download_file
    raise ex
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\tardis_dev\datasets\download.py", line 129, in _reliably_download_file
    await _download(session, url, download_path, http_proxy)
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\tardis_dev\datasets\download.py", line 169, in _download
    raise urllib.error.HTTPError(url, code=response.status, msg=error_text, hdrs=None, fp=None)
urllib.error.HTTPError: HTTP Error 401: {
  "code": 10,
  "message": "Unauthorized. Please set the 'Authorization' header with the following format: 'Bearer YOUR_API_KEY' and if you provided one already, please double check if you pasted the API key in full and without any typos. For unauthorized requests, only historical CSV market datasets for the first day of each month are available (dataset for '2019-04-03' has been requested).",
  "providedParams": {
    "exchange": "deribit",
    "dataType": "trades",
    "year": "2019",
    "month": "04",
    "day": "03",
    "symbol": "OPTIONS"
  },
  "datasetInfo": {
    "id": "OPTIONS",
    "type": "option",
    "dataTypes": [
      "trades",
      "incremental_book_L2",
      "quotes",
      "book_snapshot_5",
      "book_snapshot_25",
      "options_chain",
      "liquidations",
      "book_ticker"
    ],
    "availableSince": "2019-03-30T00:00:00.000Z",
    "availableTo": "2022-11-02T00:00:00.000Z",
    "stats": {
      "trades": 12504183,
      "bookChanges": 16022431548
    }
  }
}

Process finished with exit code 1

**Comment by thaaddeus** [comment]
Error code says it all, no API key no access.
