### ISSUE TITLE
Rename to tardis

### ISSUE THREAD

**Issue by thaaddeus** [tardis-dev/tardis-python#2]
Given new roadmap (open source real-time data handling, normalization etc) I'd like to rename this lib to `tardis` but name is already taken on https://pypi.org/project/tardis/ . @cedk assuming you don't actively use this name on pypi would you consider releasing it? Thanks!

**Comment by cedk** [comment]
Indeed I have this project https://bitbucket.org/cedk/tardis for which I had not yet made a release.
I guess you could use tardis-client as package name.

**Comment by thaaddeus** [comment]
I see, I just assumed this name is no use for you anymore, thanks for reply.
