### ISSUE TITLE
Support HTTP proxy

### ISSUE THREAD

**Issue by batterseapower** [tardis-dev/tardis-python#4]
Can you please support specifying a HTTP proxy (or using the system-configured default proxy) with this library? Corporate networks often require all traffic to go via a proxy.

`aiohttp` does have this capability: https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support

**Comment by thaaddeus** [comment]
Hi, sure I'll add it, just to be clear you're using `tardis_client.replay` functionallity?

**Comment by batterseapower** [comment]
That's right. Thanks!

**Comment by thaaddeus** [comment]
please try v1.2.12, TardisClient constructor now accepts `http_proxy`, hope that helps.

**Comment by batterseapower** [comment]
Thanks for that (and your help on the live chat earlier today regarding Huobi instrument codes). The updated TardisClient works for me, except for the fact that there is a bug with current `aiohttp` (3.7.4) proxy support on Windows (https://github.com/aio-libs/aiohttp/issues/4536). After applying the workaround there, the new Tardis client works.

**Comment by thaaddeus** [comment]
I see, thanks!
