### ISSUE TITLE
Asyncio TimeoutError

### ISSUE THREAD

**Issue by amin-nejad** [tardis-dev/tardis-python#5]
I get an `asyncio.exceptions.TimeoutError` if downloading data takes too long. Is there any way to prevent this or increase the timeout? Generally good for a few minutes until I get the error

Stack trace:
<img width="865" alt="Screenshot 2021-06-24 at 02 19 30" src="https://user-images.githubusercontent.com/44096034/123311873-8b239700-d51f-11eb-9c98-870579049c70.png">

Just running the [basic script](https://docs.tardis.dev/api/python#saving-deribit-historical-index-data-to-csv-file) from the documentation site

`python`==3.8.8
`tardis-client`==1.2.12

**Comment by thaaddeus** [comment]
Hi, yes you can increase timeout via `http_timeout` option https://github.com/tardis-dev/tardis-python/blob/master/tardis_client/tardis_client.py#L27  please also try using https://pypi.org/project/aiocsv/  as it could be that for some reason sync csv writing to file is blocking python's event loop and that is causing timeouts (as script has no CPU time to read http response as it's blocked by writing)

**Comment by amin-nejad** [comment]
Thanks!
