### ISSUE TITLE
urllib - HTTP Error 414

### ISSUE THREAD

**Issue by shahp98** [tardis-dev/tardis-python#6]
Hi. I'm trying to replay Deribit "trades" and "book" channel for 2019-03-30 for all active symbols on that day (filtered using Instruments Metadata API). Hence I have around 312 symbols for that day for which I'm trying to replay the above 2 channels.

Stack Trace:
![image](https://user-images.githubusercontent.com/32239494/123990755-aee75100-d9e7-11eb-9347-7b2ed5322e26.png)
`python`==3.8.3
`tardis-client`==1.2.12

The only change in the replay params is the list of symbols for both the channels under filters.

Is there a way I can replay data for all active symbols for a particular day for both these channels using some other approach or other clients/tardis-machine?

**Comment by thaaddeus** [comment]
Hi, one approach would be to provide empty array as symbols list (`[]`) then data for all active instruments for a given day would be returned, would that help?

**Comment by shahp98** [comment]
Yes, this helps! Thank you so much!
