### ISSUE TITLE
writes millions of temp files, never cleans up

### ISSUE THREAD

**Issue by manos** [tardis-dev/tardis-python#8]
When sync'ing large amounts of data, for example all PERP symbol data from FTX for a few months, tardis-client never cleans up its temp files in /tmp/.tardis-cache/. Left running for a day, there is currently over 3M files on my server, and left running for multiple days without manually cleaning up, it can easily run a disk out of inodes.

**Comment by thaaddeus** [comment]
Hi, yes right now, there's no cleanup function, so you'd have to remove/clear cache as needed.
Also in general it's much more efficient to request data for multiple symbols at once, vs one-by-one (it will also create less files).

**Comment by manos** [comment]
Thanks for the reply @thaaddeus! The issue with fetching multiple symbols is that if one doesn't have data at the --start date, the API doesn't just return what it has, it throws an error.
I could sort by that, e.g. bucket everything together that has data for my desired 60-day range (for example), and fetch those together.

**Comment by thaaddeus** [comment]
Actually it should still return what is available at a given day (CSV downloads would fail indeed). Can you share the sample payload that would case this issue for you by any chance? I'll investigate.

**Comment by manos** [comment]
Oh indeed, you're right - I was thinking of when I was calling the API directly. I've restructured as you recommended and fetched 60 days of all FTX PERP symbols in a few hours. InfluxDB is happily full of data :) 
Much better; thanks for the help!
