### ISSUE TITLE
[Urgent] Please fix compatibility with aiofiles. See log below

### ISSUE THREAD

**Issue by outremont** [tardis-dev/tardis-python#9]
Because no versions of tardis-client match >1.3.1,<2.0.0 tardis-client (1.3.1) depends on aiofiles (>=0.4.0,<0.5.0), tardis-client (>=1.3.1,<2.0.0) requires aiofiles (>=0.4.0,<0.5.0).

  And because sanic (22.3.2) depends on aiofiles (>=0.6.0)
   and no versions of sanic match >22.3.2,<23.0.0, tardis-client (>=1.3.1,<2.0.0) is incompatible with sanic (>=22.3.2,<23.0.0).
  So, because poseidon depends on both sanic (^22.3.2) and tardis-client (^1.3.1), version solving failed.

**Comment by thaaddeus** [comment]
should be fixed in v1.3.2
